export enum VALID_ENV_KEYS {
  OPENAI_API_KEY = "OPENAI_API_KEY",
  ANTHROPIC_API_KEY = "ANTHROPIC_API_KEY",
  GOOGLE_GEMINI_API_KEY = "GOOGLE_GEMINI_API_KEY",
  MISTRAL_API_KEY = "MISTRAL_API_KEY",
  GROQ_API_KEY = "GROQ_API_KEY",
  PERPLEXITY_API_KEY = "PERPLEXITY_API_KEY",
  AZURE_OPENAI_API_KEY = "AZURE_OPENAI_API_KEY",
  OPENROUTER_API_KEY = "OPENROUTER_API_KEY",

  OPENAI_ORGANIZATION_ID = "OPENAI_ORGANIZATION_ID",

  AZURE_OPENAI_ENDPOINT = "AZURE_OPENAI_ENDPOINT",

  // GPT-5.x Chat Models
  AZURE_GPT_52_CHAT_NAME = "AZURE_GPT_52_CHAT_NAME",
  AZURE_GPT_52_NAME = "AZURE_GPT_52_NAME",
  AZURE_GPT_51_CHAT_NAME = "AZURE_GPT_51_CHAT_NAME",
  AZURE_GPT_51_NAME = "AZURE_GPT_51_NAME",
  AZURE_GPT_5_CHAT_NAME = "AZURE_GPT_5_CHAT_NAME",
  AZURE_GPT_5_PRO_NAME = "AZURE_GPT_5_PRO_NAME",
  AZURE_GPT_5_NAME = "AZURE_GPT_5_NAME",
  AZURE_GPT_5_MINI_NAME = "AZURE_GPT_5_MINI_NAME",
  AZURE_GPT_5_NANO_NAME = "AZURE_GPT_5_NANO_NAME",

  // GPT-4.x Models
  AZURE_GPT_41_NAME = "AZURE_GPT_41_NAME",
  AZURE_GPT_41_MINI_NAME = "AZURE_GPT_41_MINI_NAME",
  AZURE_GPT_41_NANO_NAME = "AZURE_GPT_41_NANO_NAME",
  AZURE_GPT_45_PREVIEW_NAME = "AZURE_GPT_45_PREVIEW_NAME",
  AZURE_GPT_4O_NAME = "AZURE_GPT_4O_NAME",
  AZURE_GPT_4O_MINI_NAME = "AZURE_GPT_4O_MINI_NAME",
  AZURE_GPT_4_NAME = "AZURE_GPT_4_NAME",

  // O-Series Models
  AZURE_O3_NAME = "AZURE_O3_NAME",
  AZURE_O3_MINI_NAME = "AZURE_O3_MINI_NAME",
  AZURE_O3_PRO_NAME = "AZURE_O3_PRO_NAME",
  AZURE_O4_MINI_NAME = "AZURE_O4_MINI_NAME",
  AZURE_O1_NAME = "AZURE_O1_NAME",
  AZURE_O1_MINI_NAME = "AZURE_O1_MINI_NAME",
  AZURE_O1_PREVIEW_NAME = "AZURE_O1_PREVIEW_NAME",

  // Codex Models
  AZURE_GPT_52_CODEX_NAME = "AZURE_GPT_52_CODEX_NAME",
  AZURE_GPT_51_CODEX_MAX_NAME = "AZURE_GPT_51_CODEX_MAX_NAME",
  AZURE_GPT_51_CODEX_NAME = "AZURE_GPT_51_CODEX_NAME",
  AZURE_GPT_51_CODEX_MINI_NAME = "AZURE_GPT_51_CODEX_MINI_NAME",
  AZURE_GPT_5_CODEX_NAME = "AZURE_GPT_5_CODEX_NAME",
  AZURE_CODEX_MINI_NAME = "AZURE_CODEX_MINI_NAME",

  // Legacy
  AZURE_GPT_35_TURBO_NAME = "AZURE_GPT_35_TURBO_NAME",
  AZURE_GPT_45_VISION_NAME = "AZURE_GPT_45_VISION_NAME",
  AZURE_GPT_45_TURBO_NAME = "AZURE_GPT_45_TURBO_NAME",

  // Embeddings
  AZURE_EMBEDDINGS_NAME = "AZURE_EMBEDDINGS_NAME"
}
